name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to production server and pull latest code
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ vars.PRODUCTION_SSH_HOST }}
          username: ${{ vars.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          script: |
            cd /root/repos/message_backend
            git pull

