version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: postgres_vector
    restart: unless-stopped
    environment:
      POSTGRES_USER: dario
      POSTGRES_PASSWORD: superseguro123
      POSTGRES_DB: vector_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Puerto cambiado para evitar conflicto
    networks:
      - backend_network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_PORT=5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=vector_db
      - DB_POSTGRESDB_USER=dario
      - DB_POSTGRESDB_PASSWORD=superseguro123
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=otraclave123
    ports:
      - "5678:5678"  # Acceso desde tu navegador o backend NestJS local
    depends_on:
      - postgres
    networks:
      - backend_network

volumes:
  pgdata:

networks:
  backend_network:
    driver: bridge
